### ISSUE TITLE
install failed..

### ISSUE THREAD

**Issue by gwuiinKim** [snu-sf-class/swpp202201#4]
![image](https://user-images.githubusercontent.com/44941464/157047734-c8c554d2-a853-45b8-be4e-5431d70edb73.png)

ubuntu 18.04
gcc 9.1
cmake version - 3.22.3
ninja-build - 1.8.2

I ran last command of .sh file and the error occurs and installation failed.
what shoud i do ? 
just ignore and rerun the command? 

actually i rerun the command and failed again .

i used goormide , hardware specification is
disk: 40GB
memory: 4GB

**Comment by gwuiinKim** [comment]
Is there anyone who successfully install llvm? 
Please let me know..

**Comment by strikef** [comment]
It seems that the compiler crashed due to insufficient RAM.
Did you run the script on goorm IDE? Do you have the specs of CPU and RAM of your server?
