### ISSUE TITLE
Borrowing laptop (~ 3/13)

### ISSUE THREAD

**Issue by Sung-HwanLee** [snu-sf-class/swpp202201#8]
https://forms.gle/7BKksK5oz8mCgTES6
If you need to borrow a laptop from the department, submit the form above by Mar. 13th.
- You should return the laptop by the end of the semester.
- We cannot help you set up the laptop. We recommend you install OS of your taste.

**Comment by gwuiinKim** [comment]
대여된 노트북 언제 받을수있나요?

**Comment by Sung-HwanLee** [comment]
Please visit our lab (Bldg 302, Room 312-2) anytime between 2 pm - 5 pm.
